### PR TITLE
(bluefox) many adapter commands were called parallel. This PR tries t…

### PR DESCRIPTION
**Pull request by GermanBluefox**
many adapter commands were called parallel. This PR tries to remove many parallel calls.

### CODE REVIEW

**Comment by Jey-Cee** [comment]
This pull request **introduces 10 alerts** and **fixes 21** when merging d03105d2a0ea20968b13b4d703c65a5ed1892989 into c81cb1a60e9a2793dd5144725e221c6ad15d9cb0 - [view on LGTM.com](https://lgtm.com/projects/g/iobroker-community-adapters/ioBroker.upnp/rev/pr-8c07719339950c3078fc49647f39a45cbd8cb53c)

**new alerts:**

* 10 for Unneeded defensive code

**fixed alerts:**

* 17 for Unused variable, import, function or class
* 4 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Jey-Cee** [comment]
This pull request **fixes 21 alerts** when merging d632feec39926e2ccd784e463af31b0870e77bcc into c81cb1a60e9a2793dd5144725e221c6ad15d9cb0 - [view on LGTM.com](https://lgtm.com/projects/g/iobroker-community-adapters/ioBroker.upnp/rev/pr-4566b9c8396f29adfaf706ad382eba3743bc591c)

**fixed alerts:**

* 17 for Unused variable, import, function or class
* 4 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by GermanBluefox** [comment]
https://forum.iobroker.net/topic/20097/iobroker-upnp-please-test/2
Ack, that adapter do work

**Comment by Jey-Cee** [comment]
This pull request **fixes 21 alerts** when merging bbeeccd5a72bb1e78bef03e8b89d558941a891b8 into c81cb1a60e9a2793dd5144725e221c6ad15d9cb0 - [view on LGTM.com](https://lgtm.com/projects/g/iobroker-community-adapters/ioBroker.upnp/rev/pr-bba7296db67664f6975c39f410a057e720b77d57)

**fixed alerts:**

* 17 for Unused variable, import, function or class
* 4 for Useless assignment to local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Jey-Cee** [comment]
This pull request **introduces 3 alerts** and **fixes 24** when merging 3bd1f69f291fffd26f799b7ebfe1df44ef73746b into b81b12c6a7bf104ac2c92186206d22aaf3a5a09c - [view on LGTM.com](https://lgtm.com/projects/g/iobroker-community-adapters/ioBroker.upnp/rev/pr-da8a011ea4399f784d03c40a533e1e663a170c8d)

**new alerts:**

* 2 for Unneeded defensive code
* 1 for Incomplete string escaping or encoding

**fixed alerts:**

* 18 for Unused variable, import, function or class
* 4 for Useless assignment to local variable
* 1 for Replacement of a substring with itself
* 1 for Incomplete string escaping or encoding

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Jey-Cee** [comment]
This pull request **introduces 4 alerts** and **fixes 23** when merging d055be7fa112ec34880116d677231d0487802847 into b81b12c6a7bf104ac2c92186206d22aaf3a5a09c - [view on LGTM.com](https://lgtm.com/projects/g/iobroker-community-adapters/ioBroker.upnp/rev/pr-6d1b4e688e58b47e1d4e5ffaa3ed8999a9323871)

**new alerts:**

* 3 for Unneeded defensive code
* 1 for Useless assignment to local variable

**fixed alerts:**

* 18 for Unused variable, import, function or class
* 4 for Useless assignment to local variable
* 1 for Replacement of a substring with itself

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Jey-Cee** [comment]
This pull request **fixes 23 alerts** when merging e910ff272864539ed8478180b8cde072b232aef1 into b81b12c6a7bf104ac2c92186206d22aaf3a5a09c - [view on LGTM.com](https://lgtm.com/projects/g/iobroker-community-adapters/ioBroker.upnp/rev/pr-56bd2111c8e5e6e747ebb240fec1f95ffb2b6836)

**fixed alerts:**

* 18 for Unused variable, import, function or class
* 4 for Useless assignment to local variable
* 1 for Replacement of a substring with itself

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Jey-Cee** [comment]
This pull request **fixes 23 alerts** when merging a3ddb6f5cff466db2bd5aca507308546c2665c36 into b81b12c6a7bf104ac2c92186206d22aaf3a5a09c - [view on LGTM.com](https://lgtm.com/projects/g/iobroker-community-adapters/ioBroker.upnp/rev/pr-b9c54161929421aaa0da8fc1ed079ff37c7e96e3)

**fixed alerts:**

* 18 for Unused variable, import, function or class
* 4 for Useless assignment to local variable
* 1 for Replacement of a substring with itself

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Jey-Cee** [comment]
This pull request **fixes 24 alerts** when merging 691237b66c9b10c9eac281225fb2137fb5ec1428 into b81b12c6a7bf104ac2c92186206d22aaf3a5a09c - [view on LGTM.com](https://lgtm.com/projects/g/iobroker-community-adapters/ioBroker.upnp/rev/pr-329be634414b3b86a783da6277a161bdd5a93401)

**fixed alerts:**

* 18 for Unused variable, import, function or class
* 4 for Useless assignment to local variable
* 1 for Comparison between inconvertible types
* 1 for Replacement of a substring with itself

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
